language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
python:
  - "3.5"
  - "3.6"
install:
  - export CC=gcc-7
  - export CXX=g++-7
  - pip3 install -r requirements.txt
  - python3 setup.py install
script:
  - pytest -v ./test/pytest/OrderBookSnapshot.py